name = "Randy Modpack"
author = "Roview"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79fac66415ded7a3b839af7ab13ef8672498777d0201f4905bf5dbe18749a930"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
