name = "Randy Modpack"
author = "Roview"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0820ea35509f40d3cb0f423cb2ad42ee5764892ac9de5166c20945e40e4c46f"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
