name = "Randy Modpack"
author = "Roview"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21a96fd0923461c92a23cec96560829d47ab646087d2726ecf1234785a69c1f3"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
